# Generated by Django 6.1 on 2026-10-02 12:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_roadmap_learningresource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def remove_duplicate_user_skills(apps, schema_editor):
        UserSkill = apps.get_model('careers', 'UserSkill')
        duplicates = UserSkill.objects.values('user_id', 'skill_id').annotate(
            count=models.Count('id')
        ).filter(count__gt=1)
        for duplicate in duplicates:
            records = UserSkill.objects.filter(
                user_id=duplicate['user_id'],
                skill_id=duplicate['skill_id'],
            ).order_by('-proficiency', 'id')
            records.exclude(pk=records.first().pk).delete()

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='proficiency',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RunPython(remove_duplicate_user_skills, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='unique_user_skill'),
        ),
    ]
