# Generated by Django 6.1 on 2026-10-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_alter_userskill_proficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
