import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { apiFetch } from "../api";
import { Empty, ErrorState, Field, Loading, TextArea } from "../components/common";
export function Dashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { (async () => { try { const profile = await apiFetch("/profile/"); const careers = await apiFetch("/careers/"); const career = careers.find((item) => item.title.toLowerCase() === (profile.career_goal || "").toLowerCase()) || careers[0]; let readiness = null, gap = [], resources = []; if (career) { const [r, rec] = await Promise.all([apiFetch(`/careers/${career.id}/readiness-score/`), apiFetch(`/careers/${career.id}/recommendations/`)]); readiness = r; resources = rec.recommended_resources || []; try { const gapResponse = await Promise.race([apiFetch(`/careers/${career.id}/skill-gap/`), new Promise((_, reject) => setTimeout(() => reject(new Error("skill-gap-timeout")), 5000))]); gap = gapResponse.skill_gaps || []; } catch (gapError) { if (gapError.message !== "skill-gap-timeout") throw gapError; gap = (career.required_skills || []).map((required) => ({ skill: required.skill, required_importance: required.importance, current_proficiency: 0, gap: required.importance, status: "Missing" })); } } const jobs = await apiFetch("/job-descriptions/"); setData({ profile, career, readiness, gap, resources, jobs }); localStorage.setItem("career_username", profile.username || ""); } catch (err) { setError(err.message); } })(); }, []);
  if (error) return <ErrorState message={error} />; if (!data) return <Loading />;
  const gaps = data.gap.filter((item) => item.status !== "Good").slice(0, 4);
  return <><div className="welcome"><div><p className="eyebrow">YOUR PROGRESS</p><h2>Good to see you, {data.profile.username}.</h2><p className="muted">Here’s your path forward. Small steps, meaningful progress.</p></div><Link className="button primary" to="/job-analysis">Analyze a job <span>→</span></Link></div><div className="stats-grid"><article className="stat-card accent"><span>READINESS SCORE</span><strong>{data.readiness?.readiness_score ?? 0}<small>%</small></strong><p>{data.career?.title || "Choose a career goal"}</p></article><article className="stat-card"><span>SKILL GAPS</span><strong>{data.gap.filter((item) => item.status !== "Good").length}</strong><p>Skills to focus on</p></article><article className="stat-card"><span>LEARNING RESOURCES</span><strong>{data.resources.length}</strong><p>Curated for your path</p></article><article className="stat-card"><span>JOB ANALYSES</span><strong>{data.jobs.length}</strong><p>In your workspace</p></article></div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">FOCUS AREAS</p><h3>Your skill gaps</h3></div><Link to="/skill-gap">View all →</Link></div>{gaps.length ? gaps.map((item) => <div className="skill-row" key={item.skill.id}><div className="skill-info"><b>{item.skill.name}</b><span>{item.status}</span></div><div className="bar"><i style={{ width: `${Math.min((item.current_proficiency / Math.max(item.required_importance, 1)) * 100, 100)}%` }} /></div><small>{item.current_proficiency}/{item.required_importance}</small></div>) : <Empty>No skill gaps yet. You’re all caught up!</Empty>}</section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">KEEP LEARNING</p><h3>Recommended resources</h3></div><Link to="/roadmap">Explore →</Link></div>{data.resources.length ? data.resources.slice(0, 3).map((resource) => <a className="resource" href={resource.url || "#"} target="_blank" rel="noreferrer" key={resource.id}><span className="resource-icon">↗</span><div><b>{resource.title}</b><small>{resource.skill?.name} · {resource.resource_type || "Resource"}</small></div><span>→</span></a>) : <Empty>Set a matching career goal to see recommendations.</Empty>}</section></div><section className="panel recent"><div className="panel-heading"><div><p className="eyebrow">YOUR ACTIVITY</p><h3>Recent job analyses</h3></div><Link to="/job-analysis">New analysis →</Link></div>{data.jobs.length ? data.jobs.slice(0, 4).map((job) => <div className="job-row" key={job.id}><span className="company-dot">{(job.company || job.title)[0]}</span><div><b>{job.title}</b><small>{job.company || "Personal analysis"} · {new Date(job.created_at).toLocaleDateString()}</small></div><Link to={`/job-analysis/${job.id}`}>View →</Link></div>) : <Empty>Analyze your first job description to see it here.</Empty>}</section></>;
}

export function Profile() {
  const [form, setForm] = useState(null); const [skills, setSkills] = useState([]); const [skillOptions, setSkillOptions] = useState([]); const [newSkill, setNewSkill] = useState({ skill_id: "", proficiency: 1 }); const [status, setStatus] = useState(""); const [error, setError] = useState("");
  useEffect(() => { Promise.all([apiFetch("/profile/"), apiFetch("/skills/"), apiFetch("/careers/")]).then(([profile, saved, careers]) => { setForm(profile); setSkills(saved); setSkillOptions([...new Map(careers.flatMap((career) => career.required_skills.map((item) => [item.skill.id, item.skill])).filter(([, skill]) => skill)).values()]); }).catch((err) => setError(err.message)); }, []);
  if (error) return <ErrorState message={error} />; if (!form) return <Loading />;
  const update = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  async function save(event) { event.preventDefault(); setStatus(""); try { await apiFetch("/profile/", { method: "PUT", body: JSON.stringify({ career_goal: form.career_goal, education: form.education, experience: form.experience, current_skills: form.current_skills, bio: form.bio }) }); setStatus("Profile saved successfully."); } catch (err) { setError(err.message); } }
  async function addSkill(event) { event.preventDefault(); try { const saved = await apiFetch("/skills/", { method: "POST", body: JSON.stringify({ ...newSkill, skill_id: Number(newSkill.skill_id), proficiency: Number(newSkill.proficiency) }) }); setSkills([...skills, saved]); setNewSkill({ skill_id: "", proficiency: 1 }); } catch (err) { setError(err.message); } }
  async function removeSkill(id) { try { await apiFetch(`/skills/${id}/`, { method: "DELETE" }); setSkills(skills.filter((skill) => skill.id !== id)); } catch (err) { setError(err.message); } }
  return <><section className="panel form-panel"><div className="panel-heading"><div><p className="eyebrow">YOUR INFORMATION</p><h2>My profile</h2><p className="muted">Keep your profile current so your recommendations stay relevant.</p></div></div>{error && <ErrorState message={error} />}{status && <div className="success-box">{status}</div>}<form className="profile-form" onSubmit={save}><div className="form-grid"><Field label="Username" value={form.username} disabled /><Field label="Email" value={form.email} disabled /><Field label="Career goal" value={form.career_goal} onChange={update("career_goal")} placeholder="e.g. Frontend Developer" /><Field label="Education" value={form.education} onChange={update("education")} placeholder="Your degree or certification" /></div><TextArea label="Experience" value={form.experience} onChange={update("experience")} placeholder="Tell us about your professional experience" rows="4" /><TextArea label="Free-form skills (optional)" value={form.current_skills} onChange={update("current_skills")} placeholder="Additional skills or context" rows="3" /><TextArea label="Bio" value={form.bio} onChange={update("bio")} placeholder="A short introduction about yourself" rows="4" /><button className="button primary">Save changes <span>→</span></button></form></section><section className="panel form-panel"><div className="panel-heading"><div><p className="eyebrow">STRUCTURED SKILLS</p><h3>Skills and proficiency</h3><p className="muted">These records power skill gaps, readiness, and job comparisons.</p></div></div><form className="form-grid" onSubmit={addSkill}><label className="field"><span>Skill</span><select value={newSkill.skill_id} onChange={(event) => setNewSkill({ ...newSkill, skill_id: event.target.value })} required><option value="">Choose a skill</option>{skillOptions.filter((option) => !skills.some((item) => item.skill.id === option.id)).map((option) => <option value={option.id} key={option.id}>{option.name}</option>)}</select></label><label className="field"><span>Proficiency (1–5)</span><select value={newSkill.proficiency} onChange={(event) => setNewSkill({ ...newSkill, proficiency: event.target.value })}>{[1, 2, 3, 4, 5].map((level) => <option value={level} key={level}>{level}</option>)}</select></label><button className="button primary">Add skill</button></form>{skills.length ? skills.map((item) => <div className="skill-row" key={item.id}><div className="skill-info"><b>{item.skill.name}</b><span>{item.proficiency}/5</span></div><button className="button ghost" type="button" onClick={() => removeSkill(item.id)}>Remove</button></div>) : <Empty>Add your first structured skill.</Empty>}</section></>;
}

