import React from "react";
import { Link } from "react-router-dom";
export function Landing() {
  const careers = [
    ["Frontend Developer", "Build thoughtful digital experiences.", "21 skills", "lavender"],
    ["Backend Developer", "Design systems that scale.", "18 skills", "sage"],
    ["Data Analyst", "Turn questions into clear decisions.", "16 skills", "peach"],
    ["AI Engineer", "Shape what intelligent products can do.", "24 skills", "yellow"],
  ];
  return <main className="landing">
    <nav className="landing-nav landing-nav-floating">
      <Link to="/" className="logo landing-logo"><span className="logo-icon">✦</span><span>CareerPath <b>AI</b></span></Link>
      <div className="landing-nav-links"><a href="#home">Home</a><a href="#careers">Careers</a><a href="#journey">How it works</a><a href="#features">Features</a></div>
      <div><Link to="/login" className="text-link">Log in</Link><Link to="/register" className="button primary">Get started <span>→</span></Link></div>
    </nav>

    <section className="landing-hero landing-hero-product" id="home">
      <div className="landing-copy"><span className="landing-badge">✦ AI-POWERED CAREER INTELLIGENCE</span><h1>Turn your skills into your <em>next career move.</em></h1><p>Understand where you stand, discover roles that fit your potential, and get a focused plan for becoming ready.</p><div className="landing-actions"><Link to="/careers" className="button primary">Explore your career <span>→</span></Link><a href="#journey" className="button ghost">See how it works</a></div><div className="landing-proof"><span><b>01</b> Discover</span><span><b>02</b> Close gaps</span><span><b>03</b> Get ready</span></div></div>
      <div className="hero-dashboard-wrap"><div className="hero-float hero-float-ready"><b>87%</b><span>Career ready</span></div><div className="hero-float hero-float-match"><span>✦</span><b>Career match</b><small>Frontend Developer</small></div><div className="product-preview hero-dashboard"><div className="preview-top"><span className="preview-dot" /><span className="preview-dot" /><span className="preview-dot" /><small>careerpath.ai / readiness</small></div><div className="preview-body"><div className="dashboard-preview-heading"><div><span className="eyebrow">CAREER READINESS</span><h3>Frontend Developer</h3></div><strong>87<small>%</small></strong></div><div className="preview-score"><div><small>SKILLS MATCHED</small><strong>18 of 21 skills</strong></div><b>↗</b></div><div className="preview-bars"><span><i style={{ width: "88%" }} /><b>React</b></span><span><i style={{ width: "76%" }} /><b>JavaScript</b></span><span><i style={{ width: "58%" }} /><b>TypeScript</b></span></div><div className="preview-gap"><span>◎</span><div><b>Skill gap detected</b><small>2 skills need improvement</small></div><strong>→</strong></div><div className="preview-roadmap"><span className="phase-number">01</span><div><b>Recommended next step</b><small>Advanced React · 4 weeks</small></div><span>↗</span></div></div></div><div className="hero-float hero-float-skills"><b>3</b><span>Skills to improve</span></div></div>
    </section>

    <section className="landing-journey" id="journey"><div><span className="journey-icon lavender">01</span><b>Discover careers</b></div><i>→</i><div><span className="journey-icon sage">02</span><b>Analyze skills</b></div><i>→</i><div><span className="journey-icon peach">03</span><b>Find your gaps</b></div><i>→</i><div><span className="journey-icon yellow">04</span><b>Build your roadmap</b></div><i>→</i><div><span className="journey-icon rose">05</span><b>Prepare for jobs</b></div></section>

    <section className="landing-story landing-readiness" id="features"><div className="story-copy"><span className="eyebrow">YOUR CAREER, UNDERSTOOD</span><h2>Know exactly where you stand.</h2><p>Career confidence starts with a clear picture. Compare your skills to real career requirements and turn uncertainty into a next step you can act on.</p><div className="story-stats"><div><b>18/21</b><span>Skills matched</span></div><div><b>87%</b><span>Readiness score</span></div></div><Link to="/dashboard" className="text-link">View your workspace →</Link></div><div className="readiness-card"><div className="readiness-ring"><strong>87<small>%</small></strong><span>ready</span></div><div><span className="eyebrow">CAREER READINESS</span><h3>Frontend Developer</h3><div className="mini-metric"><span>Core skills</span><i><b style={{ width: "88%" }} /></i><strong>88%</strong></div><div className="mini-metric"><span>Tools & practice</span><i><b style={{ width: "74%" }} /></i><strong>74%</strong></div><div className="mini-metric"><span>Interview confidence</span><i><b style={{ width: "62%" }} /></i><strong>62%</strong></div></div></div></section>

    <section className="landing-section" id="careers"><div className="section-heading"><div><span className="eyebrow">CAREER DISCOVERY</span><h2>Find a direction that fits your potential.</h2></div><Link to="/careers" className="text-link">Explore all careers →</Link></div><div className="career-preview-grid">{careers.map(([title, description, count, tone], index) => <article className={`career-preview-card ${tone}`} key={title}><span className="career-preview-number">0{index + 1}</span><div className="career-orb" /><h3>{title}</h3><p>{description}</p><div><small>{count}</small><Link to="/careers">Explore →</Link></div></article>)}</div></section>

    <section className="landing-story landing-gap"><div className="analysis-preview"><div className="analysis-preview-head"><span className="eyebrow">AI SKILL ANALYSIS</span><span className="status-badge needs-improvement">2 focus areas</span></div>{[["React", "Your level", "88%", "Required level", "100%", "good"], ["TypeScript", "Your level", "58%", "Required level", "84%", "needs"], ["Testing", "Your level", "32%", "Required level", "76%", "missing"]].map(([skill, ownLabel, own, reqLabel, required, tone]) => <div className="analysis-preview-row" key={skill}><div><b>{skill}</b><span className={`status-badge ${tone === "good" ? "good" : tone === "needs" ? "needs-improvement" : "missing"}`}>{tone === "good" ? "Strong" : tone === "needs" ? "Moderate gap" : "Priority"}</span></div><small>{ownLabel} <strong>{own}</strong></small><i><b style={{ width: own }} /><em style={{ width: required }} /></i><small>{reqLabel} <strong>{required}</strong></small></div>)}</div><div className="story-copy"><span className="eyebrow">SKILL GAP INTELLIGENCE</span><h2>See exactly what you need to learn.</h2><p>Go beyond a generic checklist. CareerPath AI compares your current level with what the role requires and prioritizes the gaps that matter most.</p><Link to="/skill-gap" className="text-link">Analyze your skills →</Link></div></section>

    <section className="landing-section landing-roadmap-section"><div className="section-heading"><div><span className="eyebrow">PERSONALIZED ROADMAP</span><h2>From where you are to where you want to be.</h2></div><Link to="/roadmap" className="text-link">Open your roadmap →</Link></div><div className="roadmap-preview" id="roadmap"><div><span className="roadmap-dot done">✓</span><b>Current skills</b><small>Know your baseline</small></div><i /><div><span className="roadmap-dot current">02</span><b>Skill improvement</b><small>Close high-impact gaps</small></div><i /><div><span className="roadmap-dot">03</span><b>Projects</b><small>Build proof of ability</small></div><i /><div><span className="roadmap-dot">04</span><b>Career ready</b><small>Show up with confidence</small></div></div></section>

    <section className="landing-feature-grid"><article className="feature-showcase job-showcase"><div className="story-copy"><span className="eyebrow">JOB ANALYZER</span><h2>Know what a job really requires.</h2><p>Paste a job description and get an instant view of your match, missing skills, and best next actions.</p><Link to="/job-analysis" className="text-link">Analyze a job →</Link></div><div className="job-preview"><span className="eyebrow">PRODUCT DESIGNER · REMOTE</span><h4>Skill match <strong>78%</strong></h4><div><span>Matching skills</span><b>12</b></div><div><span>Developing skills</span><b>4</b></div><div><span>Priority gaps</span><b>2</b></div></div></article><article className="feature-showcase interview-showcase"><span className="eyebrow">AI MOCK INTERVIEW</span><h2>Practice before the real interview.</h2><div className="interview-bubble"><span>AI interviewer</span><b>“Tell me about a challenging project you worked on.”</b></div><div className="feedback-line"><span>Communication</span><b>Strong</b></div><div className="feedback-line"><span>Technical depth</span><b>Good</b></div><Link to="/interviews" className="text-link">Start practicing →</Link></article></section>

    <section className="landing-section assessment-section"><div className="assessment-preview"><div className="assessment-score">92<small>%</small></div><div><span className="eyebrow">ASSESSMENT COMPLETE</span><h3>JavaScript fundamentals</h3><p>Strong foundation · 23 of 25 correct</p><div className="topic-list"><span>Async patterns</span><span>Next: testing</span></div></div></div><div className="story-copy"><span className="eyebrow">ASSESSMENTS</span><h2>Turn learning into measurable progress.</h2><p>Test yourself, uncover weak areas, and get recommended topics for your next focused study session.</p><Link to="/assessments" className="text-link">Take an assessment →</Link></div></section>

    <section className="landing-ecosystem"><span className="eyebrow">ONE CONNECTED SYSTEM</span><h2>Every step of your career journey, in one place.</h2><div>{["Careers", "Skill analysis", "Skill gaps", "Roadmap", "Job analysis", "Assessment", "AI interview", "Readiness"].map((item, index) => <React.Fragment key={item}><span>{String(index + 1).padStart(2, "0")} {item}</span>{index < 7 && <i>→</i>}</React.Fragment>)}</div></section>
    <section className="landing-final-cta"><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>Your next career move starts here.</h2><p>A clearer path is closer than you think.</p><Link to="/register" className="button primary">Start your career journey <span>→</span></Link></section>
    <footer className="landing-footer"><div><Link to="/" className="logo landing-logo"><span className="logo-icon">✦</span><span>CareerPath <b>AI</b></span></Link><p>Career intelligence for your next move.</p></div><div><b>Product</b><Link to="/careers">Careers</Link><Link to="/assessments">Assessments</Link><Link to="/job-analysis">Job analyzer</Link><Link to="/interviews">Mock interview</Link></div><div><b>Workspace</b><Link to="/dashboard">Dashboard</Link><Link to="/roadmap">Roadmap</Link><Link to="/profile">Profile</Link></div><div><b>Company</b><a href="mailto:hello@careerpath.ai">Contact</a><span>Privacy</span><span>Terms</span></div></footer>
  </main>;
}

